# Site
name: "Factastic Health"
title: "Factastic Health"
description: "Healthy For Life"
logo: '/assets/images/logo.png'
favicon: '/assets/images/logo.png'
google_analytics: 'UA-110579843-1'
permalink: /:title/
# No / at the end
url: https://factastichealth.com

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
# Pagination 
paginate: 6
paginate_path: /page:num/
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

collections:
  pages:
    output: true
    permalink: "/:title/"

social_networks:
  facebook: https://www.facebook.com/factastichealth/
  twitter: https://twitter.com/FactasticHealth
  instagram: https://www.instagram.com/factastichealth/

newsletter:
  delivery_method: smtp
  options:
    address: in-v3.mailjet.com
    port: 587
